### ISSUE TITLE
Improve Iterator Interop with official BSON crate

### ISSUE THREAD

**Issue by only-cliches** [jcdyer/rawbson#1]
Excellent work on this project, seeing between 10x and 150x improvement in deserialization performance over the official crate in my tests!

However, I noticed that iterators don't work quite the same for this crate as they do for the official BSON crate.  I think it would be more convenient for people who want to just drop this library in as a replacement for deserializing to have the same API.

In that spirit, I noticed that iterating over arrays is a little different between the two libraries:

```rust
let new_doc = doc!{"list": ["allocations", "are", "slow"]};

// iterating through list of items in the official crate
for (i, item) in new_doc.get_array("list").unwrap().iter().enumerate() {
    // item is &Bson type
    match i {
        0 => assert_eq!(item.as_str().unwrap(), "allocations"),
        1 => assert_eq!(item.as_str().unwrap(), "are"),
        2 => assert_eq!(item.as_str().unwrap(), "slow"),
        _ => {}
    }
}

let mut byte_array : Vec<u8> = vec![];
new_doc.to_writer(&mut byte_array).unwrap();

let ref_doc = DocRef::new(&byte_array[..]).unwrap();
// trying the same thing...
for (i, item) in ref_doc.get_array("list").unwrap().iter().enumerate() {
    // item is &ArrayRef?  This code doesn't work....
}

// instead you seem to have to do something like this...
let list = ref_doc.get_array("list").unwrap().unwrap();

for i in 0..3 { // how would I get the array length if I didn't know it?
    match i {
        0 => assert_eq!(list.get_str(i).unwrap().unwrap(), "allocations"),
        1 => assert_eq!(list.get_str(i).unwrap().unwrap(), "are"),
        2 => assert_eq!(list.get_str(i).unwrap().unwrap(), "slow"),
        _ => {}
    }
}

```

Even if you're not focused on interop, it doesn't make sense to me that iterating over an array would just return a reference to that array on each iteration, and not a reference to the children of the array.

Thanks for all your hard work on this so far!

**Comment by jcdyer** [comment]
Hey, @only-cliches!  Thanks for including this in your benchmarks, and thanks for the usage report.  Your issue with arrays is because get_* methods return a `Result<Option<T>, _>` instead of a flat result.  As a result, you're calling `.iter()` on an `Option`, rather than an `ArrayRef`.  Notice that your working version calls the double unwrap, while the version where you try to iterate only calls `.unwrap()` a single time.  I'm working on beefing up the docs around this so hopefully it'll be clearer soon.

Edit: That is to say, the following should work:

```rust
for (i, item) in ref_doc.get_array("list").unwrap().unwrap().into_iter().enumerate() {
         match i {
        0 => assert_eq!(item.as_str().unwrap().unwrap(), "allocations"),
        1 => assert_eq!(item.as_str().unwrap().unwrap(), "are"),
        2 => assert_eq!(item.as_str().unwrap().unwrap(), "slow"),
        _ => {}
    }
}
```

and normally, I would spell that double unwrap as `?.unwrap()` instead.
 
// End edit

Some design thoughts about error handling:

 The nested `Result<Option<_>, _>` pattern shows up in a number of places around the rust ecosystem, and solves a particular problem here that the bson crate doesn't have to deal with: parsing happens at access time, not at object creation time.  As a result, we have to deal with three possible problems when accessing elements. 

1. The document is not valid BSON.  This will return `Err(Error::MalformedDocument)`.  There's not much an application programmer can do in this situation.  Usually the right thing to do here is pass the problem up to a higher abstraction layer in the application, which isn't directly concerned with manipulating the document.  (Maybe report an error to the user.  Maybe fetch a different document, and try again). 
2. The key doesn't exist.  This will return `Ok(None)`. This is a pretty normal situation, that in many cases isn't even an error.    
3. The key exists, but the element wasn't the kind expected.  This currently returns `Err(Error::UnexpectedType)`.  

The third case is the one where I'm least confident that the design is optimal.  Often at an application level, finding an object of the wrong kind is as much an error case as finding malformed BSON, but sometimes it's not.  Maybe you're expecting either an i32 or an i64.  In this case, there are two relatively ergonomic ways to handle it:

1.  Match the whole structure at once, rather than one layer at a time:
    ```rust
    let score: i64 = match doc.get_i64("score") {
        Ok(Some(score)) => score,
        Ok(None) => 0,
        Err(Error::UnexpectedType) => doc.get_i32("score")?.unwrap() as i64 // We know the element exists, but was not an i64
        Err(e) => return Err(e.into()),
    };
    ```
2.  Separate the get and as_type phases 
    ```rust
    let score = match doc.get("score")? { // get cannot return Error::UnexpectedType.  Any other error should be bubbled up.
        Some(score) => match score.element_type() { // Or try the two alternatives
            ElementType::I64 => score.as_i64().unwrap(),
            ElementType::I32 => score.as_i32().unwrap() as i64,
        }
        None => 0,
    };
    ```

There are two other alternatives that the library could do.  One would be to include the `UnexpectedType` in the inner package, possibly converting the inner type to an error, so you can still distinguish between the two cases.  The nice part about this is that it's easier to handle application level errors together while still allowing you to punt on parse errors with `?`.  The not so nice part of this is that the library now has two public error types to deal with.  The other alternative is to flatten the whole thing into a `Result<T>`, but then robust error handling will always need to rely on explicit match constructs that manually inspect the type of error produced.

I'm certainly open to other designs, but I think it would be helpful to see how error handling with the bson crate tends to look in the wild so we can optimize ergonomics for real-world usage patterns, since none of the approaches seem to be obviously optimal.

**Comment by jcdyer** [comment]
```
// how would I get the array length if I didn't know it?
```

I almost missed this question.  

Unfortunately, there's no way to know the number of elements in a bson document before iterating over it.  The structure of the document is:

```
document ::= int32 e_list "\x00" 
e_list ::= element e_list
  | ""
```
([from the spec](http://bsonspec.org/spec.html))

where the initial int32 is the number of bytes in the document, not the number of elements, so only by iterating elements until you reach `\x00` do you know the number of elements in a document.  An array is the same, but with each element having sequential ascii numeric keys.

So there are two ways to get the length of the array:

```rust
arr.into_iter().count()
```
The problem with this is that you then have to repeat the parse of the array to then access individual elements.  The more useful way in most cases is to do:

```rust
let v = arr.into_iter().collect::<Vec<rawbson::elem::Element>>();
v.len()
```

with an optional `.map(|el| el.as_str().unwrap().unwrap())` if you know you have an array of strings, for example.  

Then you can access the individual elements in O(1) time.  This costs an allocation of course.
